### ISSUE TITLE
v2.1.2 causes ImportError with Rotary

### ISSUE THREAD

**Issue by bjoernpl** [Dao-AILab/flash-attention#519] opened 2023-09-05 12:15 UTC
The changes introduced in b28ec23 cause an ImportError:
``` 
    from flash_attn.layers.rotary import apply_rotary_emb_func
File "/opt/conda/lib/python3.10/site-packages/flash_attn/layers/rotary.py", line 8, in <module>
    from flash_attn.ops.triton.rotary import apply_rotary
ModuleNotFoundError: No module named 'flash_attn.ops.triton'
```
I would expect any added dependencies to be installed with the `pip install`. Currently using 
```
pip install flash-attn --no-build-isolation
pip install git+https://github.com/HazyResearch/flash-attention.git#subdirectory=csrc/rotary
```

Reverting to `v2.1.1` solves this issue for me:
```
pip install flash-attn==2.1.1 --no-build-isolation
pip install git+https://github.com/HazyResearch/flash-attention.git@v2.1.1#subdirectory=csrc/rotary
```

**Comment by Kyeongpil** [comment] 2023-09-05 14:48
I think this is caused by missing init file.
https://github.com/Dao-AILab/flash-attention/pull/516

**Comment by Bec-k** [comment] 2023-09-05 14:52
Then need to wait when it's getting merged into main branch.

**Comment by Birch-san** [comment] 2023-09-05 15:58
I think more than just the init file is missing. creating that init file wasn't enough to fix importing of rotary embeddings for me.  
I think the entirety of [`ops/triton`](https://github.com/Dao-AILab/flash-attention/tree/main/flash_attn/ops/triton) is missing from the PyPI distribution.

**Comment by tridao** [comment] 2023-09-05 18:38
Should be fixed in v2.2.0 (might take CI 9-10 hours to finish compiling all the CUDA wheels).

**Comment by Kyeongpil** [comment] 2023-09-06 01:26
v2.2.0 was released, and `ops/triton` is successfully included :)

**Comment by Qubitium** [comment] 2023-09-06 03:34
But I am getting rotary issue https://github.com/Dao-AILab/flash-attention/issues/523  with manually compiled 2.2.0 since pypi is not ready.

**Comment by goog** [comment] 2023-09-06 07:41
Version: 2.1.2.post3 has the same problem

**Comment by tridao** [comment] 2023-09-06 07:50
> so could you give another method to get the whl not by github

We welcome contributions on this front.

**Closed** 2023-09-19 17:35 UTC
